Refactor revoke-cert
Summary:
  * Create function for asking revokation reason.
  * Create function for certificate check.
  * Create function for revoking cert.
  * Use gencrl from functions.
  * Create new revokation test for revoked certs.

diff --git a/revoke-cert b/revoke-cert
--- a/revoke-cert
+++ b/revoke-cert
@@ -57,6 +57,56 @@ function source_files() {
     source ${BIN_DIR}/defaults.conf
 }
 
+function check_certificate() {
+  local certificate=${1}; shift;
+  if [ ! -f "${certificate}" ]; then
+    echo "Could not read certificate '${certificate}', exiting."
+    exit 1
+  fi
+}
+
+function ask_revoke_reason() {
+  echo "Reason for revocation: "
+  echo
+  echo "1. unspecified"
+  echo "2. keyCompromise"
+  echo "3. CACompromise"
+  echo "4. affiliationChanged"
+  echo "5. superseded"
+  echo "6. cessationOfOperation"
+  echo "7. certificateHold"
+  echo
+  echo -n "Enter 1-7 [1]: "
+  read INDEX
+
+  [ -z "${INDEX}" ] && INDEX="1"
+
+  case $INDEX in
+  1) REASON="unspecified" ;;
+  2) REASON="keyCompromise" ;;
+  3) REASON="CACompromise" ;;
+  4) REASON="affiliationChanged" ;;
+  5) REASON="superseded" ;;
+  6) REASON="cessationOfOperation" ;;
+  7) REASON="certificateHold" ;;
+  8) echo "Unknown reason, exiting."; exit 1 ;;
+  esac
+
+  echo "You are about to revoke this certificate with reason '${REASON}'."
+  echo -n "Are you SURE you wish to continue? [y/N]: "
+  read SURE
+  if [ "${SURE}" != "y" -a "${SURE}" != "Y" ]; then
+    echo "Exiting."
+    exit 1
+  fi
+}
+
+function revoke_certificate() {
+  openssl ca \
+    -config conf/ca.conf \
+    -revoke ${CERT} \
+    -crl_reason ${REASON}
+}
 
 # -----------------------------------------------------------------------------
 # Main
@@ -64,64 +114,11 @@ function source_files() {
 parse_options "${@}"
 validate_options
 source_files
-
+check_certificate "$(fullpath ${CERT})"
 message "Revoking certificate '${CERT}'"
-
-if [ ! -f "${CERT}" ]; then
-    echo "Could not read certificate '${CERT}', exiting."
-    exit 1
-fi
-
-# Fully-qualify path to cert
-CERT=$( fullpath ${CERT} )
-
 pushd ${BIN_DIR}/.. > /dev/null
-
-echo "Reason for revocation: "
-echo
-echo "1. unspecified"
-echo "2. keyCompromise"
-echo "3. CACompromise"
-echo "4. affiliationChanged"
-echo "5. superseded"
-echo "6. cessationOfOperation"
-echo "7. certificateHold"
-echo
-echo -n "Enter 1-7 [1]: "
-read INDEX
-
-[ -z "${INDEX}" ] && INDEX="1"
-
-case $INDEX in
-    1) REASON="unspecified" ;;
-    2) REASON="keyCompromise" ;;
-    3) REASON="CACompromise" ;;
-    4) REASON="affiliationChanged" ;;
-    5) REASON="superseded" ;;
-    6) REASON="cessationOfOperation" ;;
-    7) REASON="certificateHold" ;;
-    8) echo "Unknown reason, exiting."; exit 1 ;;
-esac
-
-echo "You are about to revoke this certificate with reason '${REASON}'."
-echo -n "Are you SURE you wish to continue? [y/N]: "
-read SURE
-if [ "${SURE}" != "y" -a "${SURE}" != "Y" ]; then
-    echo "Exiting."
-    exit 1
-fi
-
-# Revoke the certificate
-openssl ca \
-           -config conf/ca.conf \
-           -revoke ${CERT} \
-           -crl_reason ${REASON}
-
-# Regenerate the CRL
-openssl ca -gencrl \
-           -config conf/ca.conf \
-           -out crl/ca.crl
-
+ask_revoke_reason
+revoke_certificate
+create_ca_crl
 popd > /dev/null
-
-message "Server certificate revoked."
+message "Certificate '${CERT}' revoked."
